// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (name, description, definition)
VALUES ($1, $2, $3)
RETURNING id, name, description, definition, is_active, created_at, updated_at
`

type CreateRuleParams struct {
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Definition  json.RawMessage `json:"definition"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule, arg.Name, arg.Description, arg.Definition)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, name, description, definition, is_active, created_at, updated_at
FROM rules
WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id int64) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRules = `-- name: ListActiveRules :many
SELECT id, name, description, definition, is_active, created_at, updated_at
FROM rules
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET name = $2, description = $3, definition = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, definition, is_active, created_at, updated_at
`

type UpdateRuleParams struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Definition  json.RawMessage `json:"definition"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, updateRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
